Resources:
  ElbHealthCheckLoggingFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: publicbuckettbd
        S3Key: elb-healthcheck-logging.zip
      Role: arn:aws:iam::318360445202:role/service-role/elb-hc-logging-role-f5x7w4ed
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Environment:
          Variables:
            Answers:
              Ref: Answers
            SequenceTokenParameter:
              Ref: SequenceParaName
            LogGroupName: 
              Ref: ElbHCLogGroupName
            LogStreamName: 
              Ref: ElbHCLogStreamName
    Metadata:
      aws:cdk:path: IddAwsCdkPdxStack/elb-healthcheck-logging
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/zPSMzbRM1JMLC/WTU7J1s3JTNKrDi5JTM7WAQrF5yTmJqUk6jmn5bmV5iWXZObn6QDZQanF+aVFyam1OgGVJRn5efrGeoYGemaKWcWZmbpFpXklmbmpekEQGgC5xHVJYAAAAA==
    Metadata:
      aws:cdk:path: IddAwsCdkPdxStack/CDKMetadata/Default
  LogSequenceTokenParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: 
        Ref: SequenceParaName
      Type: String
      Value: n.a
      Description: SSM Parameter for log stream
  ElbHCLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Ref: ElbHCLogGroupName
  ElbHCLogStream:
    Type: AWS::Logs::LogStream
    Properties:
      LogGroupName: 
        Ref: ElbHCLogGroup
      LogStreamName:
        Ref: ElbHCLogStreamName
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
  Answers:
    Type: String
    Default: Parameters from ELB doctor
    Description: Parameters from ELB doctor
  SequenceParaName: 
    Type: String
    Default: 0
    Description: System store parameter for log stream
  ElbHCLogGroupName:
    Type: String
    Default: log group name
    Description: cw log group name
  ElbHCLogStreamName:
    Type: String
    Default: log stream name
    Description: cw log stream name
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.